# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtWidgets import QWidget, QApplication, QLabel
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap  # для машинки
from PyQt5.QtGui import QPainter  # для геометрических фигур


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 242)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.qp = QPainter()
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton_flat = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_flat.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.radioButton_flat.setObjectName("radioButton_flat")
        self.radioButton_volume = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_volume.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.radioButton_volume.setObjectName("radioButton_volume")
        self.combo_figurs = QtWidgets.QComboBox(self.centralwidget)
        self.combo_figurs.setGeometry(QtCore.QRect(150, 20, 131, 21))
        self.combo_figurs.setObjectName("combo_figurs")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 131, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 0, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 161, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.combo_operations = QtWidgets.QComboBox(self.centralwidget)
        self.combo_operations.setGeometry(QtCore.QRect(180, 100, 131, 21))
        self.combo_operations.setObjectName("combo_operations")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 80, 131, 20))
        self.label_10.setObjectName("label_10")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 100, 160, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_a = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_a.setObjectName("label_a")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_a)
        self.pole_a = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pole_a.setObjectName("pole_a")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pole_a)
        self.label_b = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_b.setEnabled(True)
        self.label_b.setObjectName("label_b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_b)
        self.pole_b = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pole_b.setEnabled(True)
        self.pole_b.setObjectName("pole_b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pole_b)
        self.label_c = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_c.setEnabled(True)
        self.label_c.setObjectName("label_c")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_c)
        self.pole_c = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pole_c.setEnabled(True)
        self.pole_c.setObjectName("pole_c")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pole_c)
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(330, 130, 76, 21))
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 130, 131, 21))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_flat.setText(_translate("MainWindow", "плоские фигуры"))
        self.radioButton_volume.setText(_translate("MainWindow", "обьемные фигуры"))
        self.label.setText(_translate("MainWindow", "Установите тип фигуры:"))
        self.label_2.setText(_translate("MainWindow", "Выберите фигуру:"))
        self.label_3.setText(_translate("MainWindow", "Укажите параметры фигуры:"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.label_10.setText(_translate("MainWindow", "выберете тип расчета:"))
        self.label_a.setText(_translate("MainWindow", "сторона  a, мм:"))
        self.label_b.setText(_translate("MainWindow", "сторона  b, мм:"))
        self.label_c.setText(_translate("MainWindow", "угол, °"))
        self.label_11.setText(_translate("MainWindow", "Результат вычислений:"))
